// Auto-generated. Edit 'styles/_colors.json' instead

import * as THREE from 'three';

export const Colors = {
	white: 0xFEFEFE,
	black: 0x202020,
	good: 0x57a83b,
	bad: 0x9e3925,
	bgDark: 0x0d0c0a,
	bgPanel: 0x151618,
	textHeader: 0xc1c1cf,
	textHighlight: 0xe0d2d0,
	textAccent: 0xc5b6b4,
	textDefault: 0xa6b3c4,
	textMuted: 0x778da6,
	shadow: 0x00000080,
	border: 0x778da6,
	bgBtn: 0x151618,
	bgBtnHover: 0x2c2d2f,
	tileLight: 0x242a34,
	tileDark: 0x1d222b,
	tileBorder: 0x1d2831,
	tileHighlight: 0x1d2831,
	tileHighlight2: 0x204c45,
	tileHouse1: 0x73291b,
	tileHouse2: 0x9e3925,
	tileHouse3: 0xcf4a31,
	tileRoad1: 0x47566f,
	tileRoad2: 0x47566f,
	tileBridge: 0x47566f,
	tileWater: 0x1a4a71,
	tileTree1: 0x2b6228,
	tileTree2: 0x40943d,
	tileTree3: 0x55b853,
} as const;

export const Colors3 = {
	white: new THREE.Color(Colors.white),
	black: new THREE.Color(Colors.black),
	good: new THREE.Color(Colors.good),
	bad: new THREE.Color(Colors.bad),
	bgDark: new THREE.Color(Colors.bgDark),
	bgPanel: new THREE.Color(Colors.bgPanel),
	textHeader: new THREE.Color(Colors.textHeader),
	textHighlight: new THREE.Color(Colors.textHighlight),
	textAccent: new THREE.Color(Colors.textAccent),
	textDefault: new THREE.Color(Colors.textDefault),
	textMuted: new THREE.Color(Colors.textMuted),
	shadow: new THREE.Color(Colors.shadow),
	border: new THREE.Color(Colors.border),
	bgBtn: new THREE.Color(Colors.bgBtn),
	bgBtnHover: new THREE.Color(Colors.bgBtnHover),
	tileLight: new THREE.Color(Colors.tileLight),
	tileDark: new THREE.Color(Colors.tileDark),
	tileBorder: new THREE.Color(Colors.tileBorder),
	tileHighlight: new THREE.Color(Colors.tileHighlight),
	tileHighlight2: new THREE.Color(Colors.tileHighlight2),
	tileHouse1: new THREE.Color(Colors.tileHouse1),
	tileHouse2: new THREE.Color(Colors.tileHouse2),
	tileHouse3: new THREE.Color(Colors.tileHouse3),
	tileRoad1: new THREE.Color(Colors.tileRoad1),
	tileRoad2: new THREE.Color(Colors.tileRoad2),
	tileBridge: new THREE.Color(Colors.tileBridge),
	tileWater: new THREE.Color(Colors.tileWater),
	tileTree1: new THREE.Color(Colors.tileTree1),
	tileTree2: new THREE.Color(Colors.tileTree2),
	tileTree3: new THREE.Color(Colors.tileTree3),
} as const;